name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

# just a placeholder
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
